name: Ruff
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.11.8"
      # Update output format to enable automatic inline annotations.
      - name: Check Ruff Linting violations
        run: uvx ruff@0.12.12 check --config pyproject.toml --output-format=github .
      - name: Check Ruff Formatting violations
        run: uvx ruff@0.12.12 format --diff .
